name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    run-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Install python version 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: update pip
        run: python3 -m pip install --upgrade pip
      - name: intall all dependencies
        run: pip install -r requirements.txt